### ISSUE TITLE
Resources$NotFoundException: Unable to find resource ID #0x7f0800ae

### ISSUE THREAD

**Issue by billdizl** [PierfrancescoSoffritti/android-youtube-player#1047]
设备
品牌：Google
型号：Nexus 5X
屏幕方向：纵向
可用 RAM： 799.34 MB
可用磁盘空间： 330.4 MB
操作系统
版本：Android 8.1.0
屏幕方向：纵向
是否已取得 root 权限：否 
Caused by android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0800ae
       at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:253)
       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:760)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:630)
       at android.content.res.Resources.loadDrawable(Resources.java:886)
       at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:953)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
       at android.content.res.XResources$XTypedArray.getDrawable(XResources.java:1363)
       at android.widget.ImageView.<init>(ImageView.java:188)
       at android.widget.ImageView.<init>(ImageView.java:171)
       at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:78)
       at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:73)
       at androidx.appcompat.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:233)
       at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:152)
       at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1678)
       at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1729)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at android.view.View.inflate(View.java:23239)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.customui.DefaultPlayerUiController.<init>(DefaultPlayerUiController.kt:28)
       at com.chiquedoll.chiquedoll.view.adapter.ProductCollectionVideoAdapter$ItemProductVideoViewHolder$1.onReady(ProductCollectionVideoAdapter.kt:2661)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.YouTubePlayerBridge.sendReady$lambda$2(YouTubePlayerBridge.kt:60)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.YouTubePlayerBridge.$r8$lambda$GVQ-xTHBq2vdIFZ8RJAqXYe511c()
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.YouTubePlayerBridge$$ExternalSyntheticLambda3.run(:2)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by billdizl** [comment]
<img width="537" alt="image" src="https://github.com/PierfrancescoSoffritti/android-youtube-player/assets/30317994/f76ef9fb-c784-4572-991b-2f14c6763a19">
