### ISSUE TITLE
NetworkObserver.destroy java.lang.IllegalArgumentException - NetworkCallback was not registered

### ISSUE THREAD

**Issue by billdizl** [PierfrancescoSoffritti/android-youtube-player#1049]
Caused by java.lang.IllegalArgumentException: NetworkCallback was not registered
       at android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:4979)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.utils.NetworkObserver.destroy(NetworkObserver.kt:43)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.LegacyYouTubePlayerView.release(LegacyYouTubePlayerView.kt:168)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView.release(YouTubePlayerView.kt:197)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView.onStateChanged(YouTubePlayerView.kt:189)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
       at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.kt:266)
       at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:283)
       at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:136)
       at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:119)
       at androidx.lifecycle.ReportFragment$Companion.dispatch$lifecycle_runtime_release(ReportFragment.kt:192)
       at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPreDestroyed(ReportFragment.kt:148)
       at android.app.Activity.dispatchActivityPreDestroyed(Activity.java:1601)
       at android.app.Activity.performDestroy(Activity.java:8834)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1419)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6085)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6131)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2576)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8772)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by PierfrancescoSoffritti** [comment]
Hi, what version of the library are you using? This bug should be fixed with 12.1.0

**Comment by billdizl** [comment]
maybe 12.0.0 or 12.1.0, I am currently using the lib method to handle exceptions in the project(12.1.0)

**Comment by billdizl** [comment]
why use lib method ,because this bug https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/1047

**Comment by billdizl** [comment]
> Hi, what version of the library are you using? This bug should be fixed with 12.1.0

may be 12.0.0  
https://github.com/PierfrancescoSoffritti/android-youtube-player/pull/996  may fix it

**Comment by billdizl** [comment]
12.1.0  have this bug
