### ISSUE TITLE
Fatal Exception: android.net.ConnectivityManager$TooManyRequestsException:

### ISSUE THREAD

**Issue by billdizl** [PierfrancescoSoffritti/android-youtube-player#1051]
Lib sdk version: 12.1.0

Fatal Exception: android.net.ConnectivityManager$TooManyRequestsException:
       at android.net.ConnectivityManager.convertServiceException(ConnectivityManager.java:4143)
       at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4335)
       at android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:4864)
       at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4831)
       at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4805)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.utils.NetworkObserver.doObserveNetwork(NetworkObserver.kt:76)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.utils.NetworkObserver.observeNetwork(NetworkObserver.kt:31)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.LegacyYouTubePlayerView.initialize(LegacyYouTubePlayerView.kt:104)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView.<init>(YouTubePlayerView.kt:90)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView.<init>(YouTubePlayerView.kt:33)
       at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1192)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
       at androidx.viewpager.widget.ViewPager$3.run(ViewPager.java:273)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
       at android.view.Choreographer.doCallbacks(Choreographer.java:866)
       at android.view.Choreographer.doFrame(Choreographer.java:792)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by Micoder-dev** [comment]
Issue not fixed
