### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by billdizl** [PierfrancescoSoffritti/android-youtube-player#1056]
Fatal Exception: java.lang.IndexOutOfBoundsException:
       at android.view.ViewGroup.removeViewsInternal(ViewGroup.java:5554)
       at android.view.ViewGroup.removeViews(ViewGroup.java:5434)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.LegacyYouTubePlayerView.setCustomPlayerUi(LegacyYouTubePlayerView.kt:165)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView.setCustomPlayerUi(YouTubePlayerView.kt:178)

**Comment by PierfrancescoSoffritti** [comment]
When did this happen? Are you using custom UI?

**Comment by billdizl** [comment]
yes. i use customer
