### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by burhanz-bharatagri** [PierfrancescoSoffritti/android-youtube-player#1180]
# Bug Report

### Description of the Bug
I have added the YouTube player in the recycler view and added it as a LifecyclerObserver with the parent Fragment. There are few crashes recorded on the Firebase crashlytics dashboard. 
**Caused by java.lang.IllegalStateException
Cannot get profile for destroyed WebView.**

### Environment details
Android Version: Android 10 to Android 14

Tested devices:
- Moto G85 5G, Android 14
- Galaxy S23 FE, Android 14
- Galaxy A21s, Android 12
- Vivo Y22, Android 14

Youtube Player Library Version: 12.1.1

#### Date: Sun Nov 10 2024 20:16:08 GMT+0530 (India Standard Time)

Fatal Exception: org.chromium.base.JniAndroid$UncaughtExceptionException: Native stack trace:
#00 pc 0x00000000040eccf3 /data/app/~~maZGs5TMA5dMjtY0piL3Jg==/com.google.android.trichromelibrary_672308633-NUAtATIFhZ8eNjYyagJUIQ==/base.apk (offset 0x8dc000)
#01 pc 0x0000000002b5902b /data/app/~~maZGs5TMA5dMjtY0piL3Jg==/com.google.android.trichromelibrary_672308633-NUAtATIFhZ8eNjYyagJUIQ==/base.apk (offset 0x8dc000)
#02 pc 0x0000000003f7e83f /data/app/~~maZGs5TMA5dMjtY0piL3Jg==/com.google.android.trichromelibrary_672308633-NUAtATIFhZ8eNjYyagJUIQ==/base.apk (offset 0x8dc000)
#03 pc 0x0000000002c4cfeb /data/app/~~maZGs5TMA5dMjtY0piL3Jg==/com.google.android.trichromelibrary_672308633-NUAtATIFhZ8eNjYyagJUIQ==/base.apk (offset 0x8dc000)
#04 pc 0x000000000690d4fb /data/app/~~maZGs5TMA5dMjtY0piL3Jg==/com.google.android.trichromelibrary_672308633-NUAtATIFhZ8eNjYyagJUIQ==/base.apk (offset 0x8dc000)
#05 pc 0x0000000003fb901b /data/app/~~maZGs5TMA5dMjtY0piL3Jg==/com.google.android.trichromelibrary_672308633-NUAtATIFhZ8eNjYyagJUIQ==/base.apk (offset 0x8dc000)
#06 pc 0x0000000006927d7f /data/app/~~maZGs5TMA5dMjtY0piL3Jg==/com.google.android.trichromelibrary_672308633-NUAtATIFhZ8eNjYyagJUIQ==/base.apk (offset 0x8dc000)
#07 pc 0x0000000000009e8f /system/lib64/libutils.so
#08 pc 0x000000000000992f /system/lib64/libutils.so
#09 pc 0x00000000000ab1df /system/lib64/libandroid_runtime.so

       at org.chromium.base.JniAndroid.handleException(chromium-TrichromeWebViewGoogle6432.aab-stable-672308633:21)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:339)
       at android.os.Looper.loopOnce(Looper.java:176)
       at android.os.Looper.loop(Looper.java:328)
       at android.app.ActivityThread.main(ActivityThread.java:9244)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)

Caused by java.lang.IllegalStateException: Cannot get profile for destroyed WebView.
       at WV.c8.c(chromium-TrichromeWebViewGoogle6432.aab-stable-672308633:522)
       at WV.XY.w(chromium-TrichromeWebViewGoogle6432.aab-stable-672308633:59)
       at WV.TK.S(chromium-TrichromeWebViewGoogle6432.aab-stable-672308633:29)
       at WV.dg.a(chromium-TrichromeWebViewGoogle6432.aab-stable-672308633:38)
       at WV.cg.a(chromium-TrichromeWebViewGoogle6432.aab-stable-672308633:12)
       at org.chromium.mojo.system.impl.WatcherImpl.onHandleReady(chromium-TrichromeWebViewGoogle6432.aab-stable-672308633:3)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:339)
       at android.os.Looper.loopOnce(Looper.java:176)
       at android.os.Looper.loop(Looper.java:328)
       at android.app.ActivityThread.main(ActivityThread.java:9244)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)

**Comment by PierfrancescoSoffritti** [comment]
Please help us reproduce the issue then I'm sure we can do something about it. The stack trace does not mention the library.

**Comment by burhanz-bharatagri** [comment]
> Please help us reproduce the issue then I'm sure we can do something about it. The stack trace does not mention the library.

This didn't happen during development, so I don't have steps to reproduce it. The stack trace is from the crashlytics dashboard, and the numbers are increasing drastically. Please help if there is something to resolve this.

**Comment by burhanz-bharatagri** [comment]
@PierfrancescoSoffritti Can you help with this issue?

**Comment by PierfrancescoSoffritti** [comment]
There's not enough information here for me to help unfortunately. This might not even be related to the library.

**Comment by burhanz-bharatagri** [comment]
@pooya-mohammadhossein I am using Youtube video library in recyclerview. Is there any way to handle this crash?

**Comment by Purehi** [comment]
I found this app implemented with flutter, and the effect is pretty good
[WeTube](https://play.google.com/store/apps/details?id=free.mor.mordo.do)

**Comment by isidro89** [comment]
I think this is a WebView issue. For reference, see  https://issuetracker.google.com/issues/385775371

**Comment by Chepeman** [comment]
Happens on the app I develop as well. We found that after some times going back and forth from a fragment that contains the player, triggers the issue.
