### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by khaled-qasem** [PierfrancescoSoffritti/Android-YouTube-Player#144]
I am using release 7

Fatal Exception: java.lang.NullPointerException
       at com.pierfrancescosoffritti.youtubeplayer.player.YouTubePlayerBridge$1.run(YouTubePlayerBridge.java:69)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5017)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by PierfrancescoSoffritti** [comment]
Hi, could you please check whether one of your `YouTubePlayerListener`s is null?
