### ISSUE TITLE
till now the same crash reported on crashlytucs

### ISSUE THREAD

**Issue by hisham2007** [PierfrancescoSoffritti/Android-YouTube-Player#17]
Fatal Exception: java.lang.NullPointerException
       at java.lang.StringToReal.parseFloat(StringToReal.java:285)
       at java.lang.Float.parseFloat(Float.java:300)
       at com.pierfrancescosoffritti.youtubeplayer.YouTubePlayerBridge$9.run(YouTubePlayerBridge.java:173)
       at android.os.Handler.handleCallback(Handler.java:800)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5405)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:838)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by hisham2007** [comment]
I use 0.7.7

**Comment by PierfrancescoSoffritti** [comment]
Got it. I'll look into it asap. Or you could do it if you want, the code is public and pull requests are much appreciated :)
