### ISSUE TITLE
ActivityNotFoundException on DefaultPlayerUiController

### ISSUE THREAD

**Issue by alexparpas** [PierfrancescoSoffritti/android-youtube-player#383]
Hey, thanks for the fantastic library, works really well. Just a quick minor issue that popped on my crash logs:

Issue: No Activity found to handle Intent { act=android.intent.action.VIEW dat=http://www.youtube.com/... }

> Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=http://www.youtube.com/... }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1820)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1534)
       at android.app.Activity.startActivityForResult(Activity.java:4065)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java)
       at android.app.Activity.startActivityForResult(Activity.java:4019)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java)
       at android.app.Activity.startActivity(Activity.java:4349)
       at android.app.Activity.startActivity(Activity.java:4317)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.ui.DefaultPlayerUiController$onVideoId$1.onClick(DefaultPlayerUiController.java)
       at android.view.View.performClick(View.java:5340)
       at android.view.View$PerformClick.run(View.java:21695)
       at android.os.Handler.handleCallback(Handler.java:819)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:5943)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:817)

Haven't dug much into it, but I'm assuming this happens when the user tries to launch the youtube app when they don't have it installed?

**Comment by PierfrancescoSoffritti** [comment]
Yes, thanks for reporting the issue. We should add some checks [here](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/b82423cd603331180a7d1eff1365cbafc83482e6/core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/ui/DefaultPlayerUiController.kt#L281).

If you want, feel free to send a pull request :)

**Comment by PierfrancescoSoffritti** [comment]
This bug will be fixed in version 1.0.4. Thanks for reporting it!
