### ISSUE TITLE
When i click view full screen youtube not working

### ISSUE THREAD

**Issue by hafiz013** [PierfrancescoSoffritti/android-youtube-player#387]
hi dear, I new here. The problem that i face using this library is that it is not show up full screen like youtube library did. so how to do that. Fyi, my whole apps in potrait mode.

**Comment by PierfrancescoSoffritti** [comment]
Please refer to the examples [in the sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples/completeExample/CompleteExampleActivity.java).

**Comment by hafiz013** [comment]
sorry function depreciate/change from private FullScreenHelper fullScreenHelper = new FullScreenHelper(this); --> (View).

**Comment by hafiz013** [comment]
Unable to destroy activity {sdn.bhd.cntsolution.mamakan/sdn.bhd.cntsolution.mamakan.ViewRestaurant}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5100)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5119)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5427)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5342)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:914)
        at com.pkmmte.view.CircularImageView.refreshBitmapShader(CircularImageView.java:341)
        at com.pkmmte.view.CircularImageView.invalidate(CircularImageView.java:262)
        at android.widget.ImageView.setImageDrawable(ImageView.java:625)
        at com.bumptech.glide.request.target.DrawableImageViewTarget.setResource(DrawableImageViewTarget.java:28)
        at com.bumptech.glide.request.target.DrawableImageViewTarget.setResource(DrawableImageViewTarget.java:10)
        at com.bumptech.glide.request.target.ImageViewTarget.setResourceInternal(ImageViewTarget.java:127)
        at com.bumptech.glide.request.target.ImageViewTarget.onLoadCleared(ImageViewTarget.java:97)
        at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:333)
        at com.bumptech.glide.manager.RequestTracker.clearRemoveAndMaybeRecycle(RequestTracker.java:79)
        at com.bumptech.glide.manager.RequestTracker.clearRemoveAndRecycle(RequestTracker.java:66)
        at com.bumptech.glide.RequestManager.untrack(RequestManager.java:630)
        at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:598)
        at com.bumptech.glide.RequestManager.clear(RequestManager.java:594)
        at com.bumptech.glide.RequestManager.onDestroy(RequestManager.java:339)
        at com.bumptech.glide.manager.ActivityFragmentLifecycle.onDestroy(ActivityFragmentLifecycle.java:65)
        at com.bumptech.glide.manager.SupportRequestManagerFragment.onDestroy(SupportRequestManagerFragment.java:194)
        at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2699)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1591)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3260)
        at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:274)
        at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:419)
        at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:210)
        at android.app.Activity.performDestroy(Activity.java:7734)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1327)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5085)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5119) 
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5427) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5342) 
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:7539) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by hafiz013** [comment]
crash why

**Comment by hafiz013** [comment]
![picture1](https://user-images.githubusercontent.com/6707224/60430170-39e1b500-9c2f-11e9-9b57-7b76f7fdf4a6.jpeg)

As picture shown, the video still not full screen.

**Comment by PierfrancescoSoffritti** [comment]
I don't understand.
