### ISSUE TITLE
Application attempted to call on a destroyed WebView

### ISSUE THREAD

**Issue by bosoona** [PierfrancescoSoffritti/android-youtube-player#407]
I got error code like this

 java.lang.Throwable
        at org.chromium.android_webview.AwContents.a(PG:355)
        at org.chromium.android_webview.AwContents.b(PG:415)
        at com.android.webview.chromium.WebViewChromium.loadUrl(PG:251)
        at android.webkit.WebView.loadUrl(WebView.java:714)
        at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.WebViewYouTubePlayer$play$1.run(WebViewYouTubePlayer.kt:55)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

This happens after i programmatically remove the app and restart, will cause this everytime.

**Comment by PierfrancescoSoffritti** [comment]
Hey, what do you mean with "programmatically remove the app and restart"?

**Comment by bosoona** [comment]
Some code like this kinda
PackageManager pm = c.getPackageManager();
                if (pm != null) {
                    Intent mStartActivity = pm.getLaunchIntentForPackage(
                          c.getPackageName()
                    );
                    if (mStartActivity != null) {
                        mStartActivity.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
                        int mPendingIntentId = 223344;
                        PendingIntent mPendingIntent = PendingIntent
                                .getActivity(c, mPendingIntentId, mStartActivity,
                                        PendingIntent.FLAG_CANCEL_CURRENT);
                        AlarmManager mgr = (AlarmManager) c.getSystemService(Context.ALARM_SERVICE);
                        mgr.set(AlarmManager.RTC_WAKEUP, System.currentTimeMillis() + 100, mPendingIntent);
                        System.exit(0);

The reason behind this is because sometimes user close and app and it forget about it, as normal Android OS will GC the whole app, but not in all manufactures' phones, so we come up with a solution to force close the app and relaunch after some period of time.

Also sometimes normal kill or remove from app list, will cause the same problem, which don't allow the webview to launch and Youtube view won't load and play videos

**Comment by cyw026** [comment]
same issue.

**Comment by PierfrancescoSoffritti** [comment]
It's still not clear to me what this issue is about. The description of the issue above seems weird and the code snippet a bit hacky.

**Comment by cyw026** [comment]
When I closed the music playback service from the notification bar, I called the following code to force close my app：

@Override
    public void onDestroy() {
        super.onDestroy();
         .........
        android.os.Process.killProcess(android.os.Process.myPid());
        System.exit(0);
    }

 I got this problem when I restarted the app

**Comment by PierfrancescoSoffritti** [comment]
This looks like an hack.
