### ISSUE TITLE
at com.pierfrancescosoffritti.androidyoutubeplayer.player.a.<init>(Unknown Source)

### ISSUE THREAD

**Issue by StevenNick88** [PierfrancescoSoffritti/android-youtube-player#449]
android.content.res.Resources$NotFoundException: String resource ID #0x2040003
	at android.content.res.Resources.getText(Resources.java:329)
	at android.content.res.Resources.getString(Resources.java:427)
	at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:684)
	at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
	at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:674)
	at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:823)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:662)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:597)
	at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:319)
	at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:104)
	at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:271)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:131)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:118)
	at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:115)
	at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:268)
	at android.webkit.WebView.<init>(WebView.java:591)
	at android.webkit.WebView.<init>(WebView.java:526)
	at android.webkit.WebView.<init>(WebView.java:509)
	at com.pierfrancescosoffritti.androidyoutubeplayer.player.a.<init>(Unknown Source)
	at com.pierfrancescosoffritti.androidyoutubeplayer.player.a.<init>(Unknown Source)
	at com.pierfrancescosoffritti.androidyoutubeplayer.player.a.<init>(Unknown Source)
	at com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayerView.<init>(Unknown Source)
	at com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayerView.<init>(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.view.ViewStub.inflate(ViewStub.java:264)
	at com.tecno.boomplayer.newUI.adpter.BuzzAdapter.initVideo(BuzzAdapter.java:645)
	at com.tecno.boomplayer.newUI.adpter.BuzzAdapter.convertBuzz(BuzzAdapter.java:509)
	at com.tecno.boomplayer.newUI.adpter.BuzzAdapter.convert(BuzzAdapter.java:120)
	at com.tecno.boomplayer.newUI.adpter.BuzzAdapter.convert(BuzzAdapter.java:83)
	at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:996)
	at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:1029)
	at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:71)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
	at androidx.recyclerview.widget.LinearLayoutManager.onFocusSearchFailed(LinearLayoutManager.java:1990)
	at androidx.recyclerview.widget.RecyclerView.focusSearch(RecyclerView.java:2633)
	at android.view.ViewGroup.focusSearch(ViewGroup.java:745)
	at android.view.ViewGroup.focusSearch(ViewGroup.java:745)
	at android.view.ViewGroup.focusSearch(ViewGroup.java:745)
	at android.view.View.focusSearch(View.java:7379)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4632)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4520)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4042)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4095)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4061)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4198)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4069)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4255)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4042)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4095)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4061)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4069)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4042)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4095)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4061)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4231)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4401)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2285)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1909)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1900)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2262)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:148)
	at android.os.Looper.loop(Looper.java:151)
	at android.app.ActivityThread.main(ActivityThread.java:5631)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by PierfrancescoSoffritti** [comment]
Not very useful.

**Comment by StevenNick88** [comment]
at com.pierfrancescosoffritti.androidyoutubeplayer.player.a.(Unknown Source)
at com.pierfrancescosoffritti.androidyoutubeplayer.player.a.(Unknown Source)
at com.pierfrancescosoffritti.androidyoutubeplayer.player.a.(Unknown Source)
at com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayerView.(Unknown Source)
at com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayerView.(Unknown Source)
