### ISSUE TITLE
release YouTubePlayerView from adapter

### ISSUE THREAD

**Issue by YachikaJ** [PierfrancescoSoffritti/android-youtube-player#488]
Though my app is not crashing but it is showing me the error:

2019-11-28 11:29:55.177 14063-14063/in.app.wedpro E/ActivityThread: Activity in.app.wedpronew.BusinessPortfolioActivity has leaked IntentReceiver com.pierfrancescosoffritti.androidyoutubeplayer.core.player.utils.NetworkListener@9bad6fb that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity in.app.wedpronew.BusinessPortfolioActivity has leaked IntentReceiver com.pierfrancescosoffritti.androidyoutubeplayer.core.player.utils.NetworkListener@9bad6fb that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1167)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:950)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1339)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1319)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1313)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:596)
        at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.LegacyYouTubePlayerView.initialize(LegacyYouTubePlayerView.kt:100)
        at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.LegacyYouTubePlayerView.initialize(LegacyYouTubePlayerView.kt:118)
        at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView.<init>(YouTubePlayerView.kt:86)
        at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView.<init>(YouTubePlayerView.kt:28)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:652)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:812)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:886)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:886)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:95)
        at in.app.wedpronew.adpater.AddVideoUrlAdapter.onCreateViewHolder(**AddVideoUrlAdapter.java:56**)
        at in.app.wedpronew.adpater.AddVideoUrlAdapter.onCreateViewHolder(**AddVideoUrlAdapter.java:34**)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6794)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3336)
        at android.view.View.measure(View.java:19886)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)

I have added com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView inside the adapter and when I click the button from my main activity, I got the above error.
Can you please tell me where could I get wrong?

This is my adapter code:
     holder.youtubeItemLayoutBinding.youtubePlayerView.setVisibility(View.VISIBLE);
     holder.youtubeItemLayoutBinding.youtubePlayerView.addYouTubePlayerListener(new AbstractYouTubePlayerListener() {
                public void onReady(YouTubePlayer youTubePlayer) {
                    youTubePlayer.cueVideo(AddVideoUrlAdapter.this.getYoutubeVideoId(listingVideo.getVideoLink()), 0.0f);
                }
            });

**Comment by PierfrancescoSoffritti** [comment]
Thank you for reporting the issue. I'll look in to it. Or if you want to do it, feel free to send a pull request.

**Comment by eneim** [comment]
@YachikaJ Did you clean up the player as mentioned [here](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/LegacyYouTubePlayerView.kt#L174)?

**Comment by mallaya95** [comment]
hi, I also have this issue with the release in the adapter class. where the video some time playing in the background even if after the back press. Sometimes a youtubeplayerview will show as an error occurred in the video. I also tried ondestroy , youtube.relese in the adapter class but not working.
