### ISSUE TITLE
ndroid.view.InflateException: Binary XML file line #12: Binary XML file line #12: Error inflating class com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView

### ISSUE THREAD

**Issue by emanoel2712** [PierfrancescoSoffritti/android-youtube-player#527]
![image](https://user-images.githubusercontent.com/45019357/75312849-ef561e00-5839-11ea-89b2-c4d5528fd96f.png)
  android.view.InflateException: Binary XML file line #12: Binary XML file line #12: Error inflating class com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)

Does anyone know how to solve this error?

**Comment by emanoel2712** [comment]
> ![image](https://user-images.githubusercontent.com/45019357/75312849-ef561e00-5839-11ea-89b2-c4d5528fd96f.png)
> android.view.InflateException: Binary XML file line #12: Binary XML file line #12: Error inflating class com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
> at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
> at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
> 
> Does anyone know how to solve this error?
