### ISSUE TITLE
An error occured. Please try again later. Player ID : "etc.." 

### ISSUE THREAD

**Issue by Swordox972** [PierfrancescoSoffritti/android-youtube-player#681]
Hello, I'm working on api 19 with an emuator which is the same version and I got this error. I tried in api 28 and 29 and it works properly. I don't know the problem of the api 19 or the emulator but in the logcat it says : 
E/SoftAVC: Decoder failed: -2
E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001001)
E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -2147483648)
E/MediaCodecBridge: Cannot dequeue output buffer java.lang.IllegalStateException

**Comment by tuxxon** [comment]
E/cr_MediaCodecUtil: Failed to create MediaCodec: video/avc, codecType: 0
    java.lang.IllegalArgumentException: Failed to initialize video/avc, error 0xfffffffe
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:1864)
        at android.media.MediaCodec.createDecoderByType(MediaCodec.java:1809)
        at org.chromium.media.MediaCodecUtil.a(PG:86)
        at org.chromium.media.MediaCodecBridgeBuilder.createVideoDecoder(PG:4)

**Comment by dev-lester94** [comment]
Anyone have an update on this?
