### ISSUE TITLE
App freezes for android 10 or higher versions

### ISSUE THREAD

**Issue by Priyanshi-Z** [PierfrancescoSoffritti/android-youtube-player#728]
Hello while loading youtube video app freezes for android 10 or higher versions. I am receiving a lot of ANRs. please look into it.

` #00  pc 00000000021ede24  /data/app/~~8AUqFT3nXVKfXSFlbq1wag==/com.google.android.trichromelibrary_438910534-5cSjmtRYCGF3IrTgL_tDUg==/base.apk!libmonochrome_64.so (???)
  at J.N.MAqmDh4t (N.java)
  at org.chromium.content.browser.framehost.NavigationControllerImpl.j (NavigationControllerImpl.java:15)
  at org.chromium.android_webview.AwContents.w (AwContents.java:35)
  at org.chromium.android_webview.AwContents.v (AwContents.java:19)
  at com.android.webview.chromium.WebViewChromium.loadDataWithBaseURL (WebViewChromium.java:6)
  at android.webkit.WebView.loadDataWithBaseURL (WebView.java:876)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.a.a (a.java)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.a.a (a.java)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.a.a (a.java)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.a.a (a.java)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.a.a (a.java)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.a.a (a.java)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayerView$1.call (YouTubePlayerView.java)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayerView.initialize (YouTubePlayerView.java)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayerView.initialize (YouTubePlayerView.java)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayerView.initialize (YouTubePlayerView.java)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayerView.initialize (YouTubePlayerView.java)
  at com.sample.TvItemVM.setUrlInVideoPlayer (TvItemVM.java:38)
  at com.sample.viewmodel.fragment.home.TvItemVM.<init> (TvItemVM.java:30)
  at com.sample.adapter.HomeTvItemAdapter.onBindViewHolder (HomeTvItemAdapter.java:39)
  at com.sample.home.HomeTvItemAdapter.onBindViewHolder (HomeTvItemAdapter.java:19)
  at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder (RecyclerView.java:6781)
  at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder (RecyclerView.java:6823)
  at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline (RecyclerView.java:5752)
  at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline (RecyclerView.java:6019)
  at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition (RecyclerView.java:5858)
  at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition (RecyclerView.java:5854)
  at androidx.recyclerview.widget.LayoutState.next (LayoutState.java:100)
  at androidx.recyclerview.widget.StaggeredGridLayoutManager.fill (StaggeredGridLayoutManager.java:1609)
  at androidx.recyclerview.widget.StaggeredGridLayoutManager.onLayoutChildren (StaggeredGridLayoutManager.java:683)
  at androidx.recyclerview.widget.StaggeredGridLayoutManager.onLayoutChildren (StaggeredGridLayoutManager.java:605)
  at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2 (RecyclerView.java:3924)
  at androidx.recyclerview.widget.RecyclerView.onMeasure (RecyclerView.java:3336)
  at android.view.View.measure (View.java:25671)
  at android.widget.RelativeLayout.measureChildHorizontal (RelativeLayout.java:735)
  at android.widget.RelativeLayout.onMeasure (RelativeLayout.java:481)
  at android.view.View.measure (View.java:25671)
  at android.widget.RelativeLayout.measureChildHorizontal (RelativeLayout.java:735)
  at android.widget.RelativeLayout.onMeasure (RelativeLayout.java:481)
  at android.view.View.measure (View.java:25671)
  at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins (RecyclerView.java:9119)
  at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk (LinearLayoutManager.java:1583)
  at androidx.recyclerview.widget.LinearLayoutManager.fill (LinearLayoutManager.java:1517)
  at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren (LinearLayoutManager.java:612)
  at com.sample.utils.WrapContentLinearLayoutManager.onLayoutChildren (WrapContentLinearLayoutManager.java:28)
  at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2 (RecyclerView.java:3924)
  at androidx.recyclerview.widget.RecyclerView.onMeasure (RecyclerView.java:3336)
  at android.view.View.measure (View.java:25671)
  at android.widget.RelativeLayout.measureChildHorizontal (RelativeLayout.java:735)
  at android.widget.RelativeLayout.onMeasure (RelativeLayout.java:481)
  at android.view.View.measure (View.java:25671)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6987)
  at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild (CoordinatorLayout.java:733)
  at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild (HeaderScrollingViewBehavior.java:95)
  at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild (AppBarLayout.java:1556)
  at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure (CoordinatorLayout.java:803)
  at android.view.View.measure (View.java:25671)
  at android.widget.RelativeLayout.measureChildHorizontal (RelativeLayout.java:735)
  at android.widget.RelativeLayout.onMeasure (RelativeLayout.java:481)
  at android.view.View.measure (View.java:25671)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6987)
  at android.widget.FrameLayout.onMeasure (FrameLayout.java:194)
  at android.view.View.measure (View.java:25671)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6987)
  at android.widget.FrameLayout.onMeasure (FrameLayout.java:194)
  at android.view.View.measure (View.java:25671)
  at android.widget.RelativeLayout.measureChildHorizontal (RelativeLayout.java:735)
  at android.widget.RelativeLayout.onMeasure (RelativeLayout.java:481)
  at android.view.View.measure (View.java:25671)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6987)
  at android.widget.FrameLayout.onMeasure (FrameLayout.java:194)
  at androidx.appcompat.widget.ContentFrameLayout.onMeasure (ContentFrameLayout.java:143)
  at android.view.View.measure (View.java:25671)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6987)
  at android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1552)
  at android.widget.LinearLayout.measureVertical (LinearLayout.java:842)
  at android.widget.LinearLayout.onMeasure (LinearLayout.java:721)
  at android.view.View.measure (View.java:25671)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6987)
  at android.widget.FrameLayout.onMeasure (FrameLayout.java:194)
  at android.view.View.measure (View.java:25671)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6987)
  at android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1552)
  at android.widget.LinearLayout.measureVertical (LinearLayout.java:842)
  at android.widget.LinearLayout.onMeasure (LinearLayout.java:721)
  at android.view.View.measure (View.java:25671)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6987)
  at android.widget.FrameLayout.onMeasure (FrameLayout.java:194)
  at com.android.internal.policy.DecorView.onMeasure (DecorView.java:753)
  at android.view.View.measure (View.java:25671)
  at android.view.ViewRootImpl.performMeasure (ViewRootImpl.java:3675)
  at android.view.ViewRootImpl.measureHierarchy (ViewRootImpl.java:2466)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2741)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:2152)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:8675)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1352)
  at android.view.Choreographer.doCallbacks (Choreographer.java:1149)
  at android.view.Choreographer.doFrame (Choreographer.java:1049)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1333)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:233)
  at android.app.ActivityThread.main (ActivityThread.java:8010)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:631)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:978)
`

Devices in which I am experiencing this issue is :

OnePlus 8 Pro-Android 11 (SDK 30)
OnePlus OnePlus6T-Android 10 (SDK 29)
Samsung Galaxy M31-Android 11 (SDK 30)
OnePlus 6 - Android 10 (SDK 29)

@PierfrancescoSoffritti  need serious attention on this :)

**Comment by amrashraf1992** [comment]
I have same issue with Android 10 Also 
Over Oneplus 6T and Oneplus 8T

@PierfrancescoSoffritti 

We need your urgent support

**Comment by Priyanshi-Z** [comment]
@PierfrancescoSoffritti We need urgent support :)

**Comment by Priyanshi-Z** [comment]
@amrashraf1992 did you found any solution yet ?

**Comment by PierfrancescoSoffritti** [comment]
This is not enough information to say anything. Be more specific if you want people to help you.

I noticed YouTube is not working on desktop too today, maybe they're rolling out a buggy update. I suggest waiting a day or two.

**Comment by Priyanshi-Z** [comment]
@PierfrancescoSoffritti ANR's have increased a lot in last 2-3 days as soon as I have rolled out my app. All of them have this same reason. This issue is not related with youtube it is linked with Android 10 and above versions. Because all the anr's I have found are in android 10+version. And What all details should I update?

**Comment by PierfrancescoSoffritti** [comment]
A stack trace or some meaningful log would be helpful.

**Comment by Priyanshi-Z** [comment]
> "main" prio=5 tid=1 Native
#00  pc 0000000002bdd3c4  /data/app/~~7psGITxl9RZ1oLQqrUw_bw==/com.google.android.trichromelibrary_443006634-2IA8rc_NtVduP-s7oT-EjA==/base.apk!libmonochrome_64.so (???)
  at J.N.MAqmDh4t (N.java)
  at org.chromium.content.browser.framehost.NavigationControllerImpl.j (NavigationControllerImpl.java:15)
  at org.chromium.android_webview.AwContents.w (AwContents.java:35)
  at org.chromium.android_webview.AwContents.v (AwContents.java:19)
  at com.android.webview.chromium.WebViewChromium.loadDataWithBaseURL (WebViewChromium.java:6)
  at android.webkit.WebView.loadDataWithBaseURL (WebView.java:860)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.a.a (a.java)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.a.a (a.java)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.a.a (a.java)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.a.a (a.java)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.a.a (a.java)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.a.a (a.java)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayerView$1.call (YouTubePlayerView.java)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayerView.initialize (YouTubePlayerView.java)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayerView.initialize (YouTubePlayerView.java)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayerView.initialize (YouTubePlayerView.java)
  at com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayerView.initialize (YouTubePlayerView.java)
  at com..x.x.x.x.ItemVM.setUrlInVideoPlayer (ItemVM.java:38)
  at com..x.x.x.x.<init> (ItemVM.java:30)
  at com.x.x.x.x.onBindViewHolder (TvItemAdapter.java:39)
  at com.x.x.x.x.x.onBindViewHolder (TvItemAdapter.java:19)
  at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder (RecyclerView.java:6781)
  at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder (RecyclerView.java:6823)
  at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline (RecyclerView.java:5752)
  at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline (RecyclerView.java:6019)
  at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition (RecyclerView.java:5858)
  at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition (RecyclerView.java:5854)
  at androidx.recyclerview.widget.LayoutState.next (LayoutState.java:100)
  at androidx.recyclerview.widget.StaggeredGridLayoutManager.fill (StaggeredGridLayoutManager.java:1609)
  at androidx.recyclerview.widget.StaggeredGridLayoutManager.onLayoutChildren (StaggeredGridLayoutManager.java:683)
  at androidx.recyclerview.widget.StaggeredGridLayoutManager.onLayoutChildren (StaggeredGridLayoutManager.java:605)
  at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2 (RecyclerView.java:3924)
  at androidx.recyclerview.widget.RecyclerView.onMeasure (RecyclerView.java:3336)
  at android.view.View.measure (View.java:27131)
  at android.widget.RelativeLayout.measureChildHorizontal (RelativeLayout.java:735)
  at android.widget.RelativeLayout.onMeasure (RelativeLayout.java:481)
  at android.view.View.measure (View.java:27131)
  at android.widget.RelativeLayout.measureChildHorizontal (RelativeLayout.java:735)
  at android.widget.RelativeLayout.onMeasure (RelativeLayout.java:481)
  at android.view.View.measure (View.java:27131)
  at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins (RecyclerView.java:9119)
  at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk (LinearLayoutManager.java:1583)
  at androidx.recyclerview.widget.LinearLayoutManager.fill (LinearLayoutManager.java:1517)
  at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren (LinearLayoutManager.java:612)
  at .x.x.x.x.utils.WrapContentLinearLayoutManager.onLayoutChildren (WrapContentLinearLayoutManager.java:28)
  at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2 (RecyclerView.java:3924)
  at androidx.recyclerview.widget.RecyclerView.onMeasure (RecyclerView.java:3336)
  at android.view.View.measure (View.java:27131)
  at android.widget.RelativeLayout.measureChildHorizontal (RelativeLayout.java:735)
  at android.widget.RelativeLayout.onMeasure (RelativeLayout.java:481)
  at android.view.View.measure (View.java:27131)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:7951)
  at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild (CoordinatorLayout.java:733)
  at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild (HeaderScrollingViewBehavior.java:95)
  at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild (AppBarLayout.java:1556)
  at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure (CoordinatorLayout.java:803)
  at android.view.View.measure (View.java:27131)
  at android.widget.RelativeLayout.measureChildHorizontal (RelativeLayout.java:735)
  at android.widget.RelativeLayout.onMeasure (RelativeLayout.java:481)
  at android.view.View.measure (View.java:27131)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:7951)
  at android.widget.FrameLayout.onMeasure (FrameLayout.java:194)
  at android.view.View.measure (View.java:27131)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:7951)
  at android.widget.FrameLayout.onMeasure (FrameLayout.java:194)
  at android.view.View.measure (View.java:27131)
  at android.widget.RelativeLayout.measureChildHorizontal (RelativeLayout.java:735)
  at android.widget.RelativeLayout.onMeasure (RelativeLayout.java:481)
  at android.view.View.measure (View.java:27131)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:7951)
  at android.widget.FrameLayout.onMeasure (FrameLayout.java:194)
  at androidx.appcompat.widget.ContentFrameLayout.onMeasure (ContentFrameLayout.java:143)
  at android.view.View.measure (View.java:27131)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:7951)
  at android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1552)
  at android.widget.LinearLayout.measureVertical (LinearLayout.java:842)
  at android.widget.LinearLayout.onMeasure (LinearLayout.java:721)
  at android.view.View.measure (View.java:27131)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:7951)
  at android.widget.FrameLayout.onMeasure (FrameLayout.java:194)
  at android.view.View.measure (View.java:27131)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:7951)
  at android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1552)
  at android.widget.LinearLayout.measureVertical (LinearLayout.java:842)
  at android.widget.LinearLayout.onMeasure (LinearLayout.java:721)
  at android.view.View.measure (View.java:27131)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:7951)
  at android.widget.FrameLayout.onMeasure (FrameLayout.java:194)
  at com.android.internal.policy.DecorView.onMeasure (DecorView.java:1173)
  at android.view.View.measure (View.java:27131)
  at android.view.ViewRootImpl.performMeasure (ViewRootImpl.java:4139)
  at android.view.ViewRootImpl.measureHierarchy (ViewRootImpl.java:2893)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:3156)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:2575)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:9910)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1010)
  at android.view.Choreographer.doCallbacks (Choreographer.java:809)
  at android.view.Choreographer.doFrame (Choreographer.java:744)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:995)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8506)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
  
    #00  pc 000000000004b50c  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
  #00  pc 00000000001b092c  /apex/com.android.art/lib64/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+148)
  #00  pc 00000000005d3404  /apex/com.android.art/lib64/libart.so (art::ThreadPool::GetTask(art::Thread*)+120)
  #00  pc 00000000005d26a8  /apex/com.android.art/lib64/libart.so (art::ThreadPoolWorker::Run()+144)
  #00  pc 00000000005d2158  /apex/com.android.art/lib64/libart.so (art::ThreadPoolWorker::Callback(void*)+192)
  #00  pc 00000000000b0128  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64)
  #00  pc 000000000005060c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
  
  
"FinalizerDaemon" daemon prio=5 tid=9 Waiting
    at java.lang.Object.wait (Native method)
  at java.lang.Object.wait (Object.java:442)
  at java.lang.ref.ReferenceQueue.remove (ReferenceQueue.java:190)
  at java.lang.ref.ReferenceQueue.remove (ReferenceQueue.java:211)
  at java.lang.Daemons$FinalizerDaemon.runInternal (Daemons.java:273)
  at java.lang.Daemons$Daemon.run (Daemons.java:139)
  at java.lang.Thread.run (Thread.java:923)
  
  
  
  @PierfrancescoSoffritti this

**Comment by amrashraf1992** [comment]
> @amrashraf1992 did you found any solution yet ?

I can't find but i have same behavior but not stainable.

**Comment by amrashraf1992** [comment]
> This is not enough information to say anything. Be more specific if you want people to help you.
> 
> I noticed YouTube is not working on desktop too today, maybe they're rolling out a buggy update. I suggest waiting a day or two.

I think this bug related to chromium version after android 10

**Comment by Priyanshi-Z** [comment]
@PierfrancescoSoffritti I don't think so it is related to buggy release of youtube as it is not creating any issue in android version below 10. It works seamlessly

**Comment by amrashraf1992** [comment]
2021-04-21 21:48:54.135 I/chromium: [INFO:CONSOLE(638)] "Unrecognized feature: 'picture-in-picture'.", source: https://www.youtube.com/s/player/ae5b2092/www-widgetapi.vflset/www-widgetapi.js (638)

**Comment by amrashraf1992** [comment]
@PierfrancescoSoffritti @Priyanshi-Z i think this crash is related to webview bug "Chromium"

**Comment by amrashraf1992** [comment]
2021-04-21 22:44:24.601 W/.lyticshub.ino: Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
2021-04-21 22:44:24.607 D/BluetoothAdapter: java.lang.Throwable
        at android.bluetooth.BluetoothAdapter.<init>(BluetoothAdapter.java:762)
        at android.bluetooth.BluetoothAdapter.getDefaultAdapter(BluetoothAdapter.java:735)
        at android.bluetooth.BluetoothManager.<init>(BluetoothManager.java:72)
        at android.app.SystemServiceRegistry$10.createService(SystemServiceRegistry.java:325)
        at android.app.SystemServiceRegistry$10.createService(SystemServiceRegistry.java:322)
        at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:1722)
        at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:1402)
        at android.app.ContextImpl.getSystemService(ContextImpl.java:1940)
        at android.content.ContextWrapper.getSystemService(ContextWrapper.java:803)
        at Zg.getSystemService(chromium-TrichromeWebViewGoogle6432.aab-stable-438910534:6)
        at org.chromium.media.AudioManagerAndroid.init(chromium-TrichromeWebViewGoogle6432.aab-stable-438910534:17)
2021-04-21 22:44:25.450 I/chromium: [INFO:CONSOLE(638)] "Unrecognized feature: 'picture-in-picture'.", source: https://www.youtube.com/s/player/ae5b2092/www-widgetapi.vflset/www-widgetapi.js (638)

**Comment by curiousbee2020** [comment]
Did anyone figure out what the issue was/is?

**Comment by Priyanshi-Z** [comment]
@curiousbee2020 Not yet. What is the issue which you are facing ? Can you give us little details regarding your issue

**Comment by amrashraf1992** [comment]
2021-04-28 16:15:41.508 E/chromium: [ERROR:web_contents_delegate.cc(179)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.

**Comment by amrashraf1992** [comment]
2021-04-28 16:28:51.209 I/chromium: [INFO:CONSOLE(638)] "Unrecognized feature: 'clipboard-write'.", source: https://www.youtube.com/s/player/cb5bd7e6/www-widgetapi.vflset/www-widgetapi.js (638)
2021-04-28 16:28:51.209 I/chromium: [INFO:CONSOLE(638)] "Unrecognized feature: 'picture-in-picture'.", source: https://www.youtube.com/s/player/cb5bd7e6/www-widgetapi.vflset/www-widgetapi.js (638)
2021-04-28 16:28:52.967 W/System.err: State UNSTARTED 2021-04-28T16:28:52.967000+02:00
2021-04-28 16:28:53.060 I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
2021-04-28 16:28:53.060 D/AudioTrack: set(): streamType 3, sampleRate 48000, format 0x5, channelMask 0x3, frameCount 0, flags #8, notificationFrames 0, sessionId 737, transferType 0, uid -1, pid -1
2021-04-28 16:28:53.064 I/cr_MediaCodecBridge: create MediaCodec video decoder, mime video/x-vnd.on2.vp9
2021-04-28 16:28:53.064 I/MediaCodec: name: video/x-vnd.on2.vp9
2021-04-28 16:28:53.076 I/OMXClient: IOmx service obtained
2021-04-28 16:28:53.090 I/MediaCodec: configure format is :{max-height=360, max-width=640, mime=video/x-vnd.on2.vp9, width=640, max-input-size=86400, height=360}
2021-04-28 16:28:53.091 W/MediaCodec: RETYR:0
2021-04-28 16:28:53.091 D/SurfaceUtils: connecting to surface 0xbf803808, reason connectToSurface
2021-04-28 16:28:53.091 I/MediaCodec: [OMX.qcom.video.decoder.vp9] setting surface generation to 31915025
2021-04-28 16:28:53.091 D/SurfaceUtils: disconnecting from surface 0xbf803808, reason connectToSurface(reconnect)
2021-04-28 16:28:53.091 D/SurfaceUtils: connecting to surface 0xbf803808, reason connectToSurface(reconnect)
2021-04-28 16:28:53.092 I/ExtendedACodec: setupVideoDecoder()
2021-04-28 16:28:53.093 I/ExtendedACodec: Decoder will be in frame by frame mode
2021-04-28 16:28:53.098 I/MediaCodec: start
2021-04-28 16:28:53.107 D/SurfaceUtils: set up nativeWindow 0xbf803808 for 640x360, color 0x7fa30c06, rotation 0, usage 0x20002900
2021-04-28 16:28:53.124 D/SurfaceUtils: set up nativeWindow 0xbf803808 for 640x360, color 0x7fa30c06, rotation 0, usage 0x20002900
2021-04-28 16:28:53.139 W/AudioManager: Use of stream types is deprecated for operations other than volume control
2021-04-28 16:28:53.139 W/AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
2021-04-28 16:28:53.142 D/AudioTrack: stop() called with 3844 frames delivered
2021-04-28 16:28:53.153 W/cr_MediaCodecBridge: Releasing: OMX.qcom.video.decoder.vp9
2021-04-28 16:28:53.170 D/SurfaceUtils: disconnecting from surface 0xbf803808, reason disconnectFromSurface
2021-04-28 16:28:53.174 W/cr_MediaCodecBridge: Codec released
2021-04-28 16:28:53.174 I/cr_MediaCodecBridge: create MediaCodec video decoder, mime video/x-vnd.on2.vp9
2021-04-28 16:28:53.175 I/MediaCodec: name: video/x-vnd.on2.vp9
2021-04-28 16:28:53.178 I/OMXClient: IOmx service obtained
2021-04-28 16:28:53.187 I/MediaCodec: configure format is :{max-height=360, max-width=640, mime=video/x-vnd.on2.vp9, width=640, max-input-size=86400, height=360}
2021-04-28 16:28:53.188 W/MediaCodec: RETYR:0
2021-04-28 16:28:53.188 D/SurfaceUtils: connecting to surface 0xbf803808, reason connectToSurface
2021-04-28 16:28:53.188 I/MediaCodec: [OMX.qcom.video.decoder.vp9] setting surface generation to 31915026
2021-04-28 16:28:53.188 D/SurfaceUtils: disconnecting from surface 0xbf803808, reason connectToSurface(reconnect)
2021-04-28 16:28:53.188 D/SurfaceUtils: connecting to surface 0xbf803808, reason connectToSurface(reconnect)
2021-04-28 16:28:53.189 I/ExtendedACodec: setupVideoDecoder()
2021-04-28 16:28:53.190 I/ExtendedACodec: Decoder will be in frame by frame mode
2021-04-28 16:28:53.194 I/MediaCodec: start
2021-04-28 16:28:53.194 I/AudioTrack: wait:83333
2021-04-28 16:28:53.200 D/SurfaceUtils: set up nativeWindow 0xbf803808 for 640x360, color 0x7fa30c06, rotation 0, usage 0x20002900
2021-04-28 16:28:53.218 D/SurfaceUtils: set up nativeWindow 0xbf803808 for 640x360, color 0x7fa30c06, rotation 0, usage 0x20002900
2021-04-28 16:28:53.736 E/chromium: [ERROR:web_contents_delegate.cc(179)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
2021-04-28 16:28:53.736 E/chromium: [ERROR:web_contents_delegate.cc(179)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
2021-04-28 16:28:53.737 W/cr_media: Requires MODIFY_AUDIO_SETTINGS and RECORD_AUDIO. No audio device will be available for recording

**Comment by amrashraf1992** [comment]
@PierfrancescoSoffritti Any Update about our issue

**Comment by Priyanshi-Z** [comment]
@PierfrancescoSoffritti Yes we need a urgent support from your end. As this ANR is destroying vitals of my app

**Comment by PierfrancescoSoffritti** [comment]
I don't think the ANR is coming from the player, but the code is open source, feel free to investigate the issue.

**Comment by Priyanshi-Z** [comment]
Hello, Thanks for your response. Can it be the case if we are using multiple instance of player inside recycler view ? Can this be the reason?

**Comment by PierfrancescoSoffritti** [comment]
I doubt it, but you can look at the example in the sample app to see if something's different in your implementation.

**Comment by Priyanshi-Z** [comment]
@amrashraf1992 @curiousbee2020 were you able to figure out any fix for it ?

**Comment by Priyanshi-Z** [comment]
@amrashraf1992 @curiousbee2020 pls try the fix suggested here if it fixes your case :

https://stackoverflow.com/questions/67304874/android-webview-chromium-shows-anr-when-method-webview-loadurl-is-called-with?noredirect=1#comment120806256_67304874

**Comment by snomula05** [comment]
How can i play youtube video not other than v=id,how can we play direct youtube link.please help me
