### ISSUE TITLE
WebView Crash with android 12 with device Samsung Note 20

### ISSUE THREAD

**Issue by nguyenngocthai05121996** [PierfrancescoSoffritti/android-youtube-player#816]
Someone help me with issues . App always crash  device Samsung Note 20 with log below :
E/WebViewFactory: error instantiating provider
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:355)
        at android.webkit.WebView.getFactory(WebView.java:2594)
        at android.webkit.WebView.ensureProviderCreated(WebView.java:2588)
        at android.webkit.WebView.setOverScrollMode(WebView.java:2675)
        at android.view.View.<init>(View.java:5567)
        at android.view.View.<init>(View.java:5742)
        at android.view.ViewGroup.<init>(ViewGroup.java:720)
        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:58)
        at android.webkit.WebView.<init>(WebView.java:421)
        at android.webkit.WebView.<init>(WebView.java:363)
        at android.webkit.WebView.<init>(WebView.java:345)
        at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.WebViewYouTubePlayer.<init>(WebViewYouTubePlayer.kt:27)
        at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.WebViewYouTubePlayer.<init>(WebViewYouTubePlayer.kt:26)
        at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.LegacyYouTubePlayerView.<init>(LegacyYouTubePlayerView.kt:32)
        at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.LegacyYouTubePlayerView.<init>(LegacyYouTubePlayerView.kt:29)
        at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView.<init>(YouTubePlayerView.kt:28)
        at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView.<init>(YouTubePlayerView.kt:26)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)

**Comment by nguyenngocthai05121996** [comment]
Caused by: java.lang.RuntimeException: Package not found: com.google.android.webview
        at android.webkit.WebViewDelegate.getPackageId(WebViewDelegate.java:159)
        at zC0.b(Unknown Source:2)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.f(Unknown Source:161)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(chromium-TrichromeWebViewGoogle6432.aab-stable-469209834:12)
        at com.android.webview.chromium.WebViewChromiumFactoryProviderForS.<init>(Unknown Source:0)
        at com.android.webview.chromium.WebViewChromiumFactoryProviderForS.create(Unknown Source:2)

**Comment by Leeonardoo** [comment]
I'm having the same issue but on a Galaxy J7(2016) running on Oreo. Have you found a solution?

**Comment by ThaiNguyen112** [comment]
> I'm having the same issue but on a Galaxy J7(2016) running on Oreo. Have you found a solution?

Can you try update WebView Android System from CHPlay  . My Issue resolved
