### ISSUE TITLE
Error inflating class com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView

### ISSUE THREAD

**Issue by billdizl** [PierfrancescoSoffritti/android-youtube-player#876]
Caused by android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:428)
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:493)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:348)
       at android.webkit.WebView.getFactory(WebView.java:2594)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2588)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2675)
       at android.view.View.<init>(View.java:5567)
       at android.view.View.<init>(View.java:5742)
       at android.view.ViewGroup.<init>(ViewGroup.java:720)
       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:58)
       at android.webkit.WebView.<init>(WebView.java:421)
       at android.webkit.WebView.<init>(WebView.java:363)
       at android.webkit.WebView.<init>(WebView.java:345)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.WebViewYouTubePlayer.<init>(WebViewYouTubePlayer.kt:27)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.WebViewYouTubePlayer.<init>(WebViewYouTubePlayer.kt:26)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.LegacyYouTubePlayerView.<init>(LegacyYouTubePlayerView.kt:32)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.LegacyYouTubePlayerView.<init>(LegacyYouTubePlayerView.kt:29)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView.<init>(YouTubePlayerView.kt:28)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView.<init>(YouTubePlayerView.kt:26)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at android.view.LayoutInflater.createView(LayoutInflater.java:858)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
       at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
       at androidx.databinding.ViewDataBinding.inflateInternal(ViewDataBinding.java:1368)
       at com.chiquedoll.chiquedoll.databinding.ItemProductVideoCategoryViewBinding.inflate(ItemProductVideoCategoryViewBinding.java:134)
       at com.chiquedoll.chiquedoll.databinding.ItemProductVideoCategoryViewBinding.inflate(ItemProductVideoCategoryViewBinding.java:120)
       at com.chiquedoll.chiquedoll.view.adapter.ProductCollectionVideoNoFootAdapter.onCreateViewHolder(ProductCollectionVideoNoFootAdapter.kt:227)
       at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7295)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6416)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
       at androidx.recyclerview.widget.LayoutState.next(LayoutState.java:98)
       at androidx.recyclerview.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1581)
       at androidx.recyclerview.widget.StaggeredGridLayoutManager.scrollBy(StaggeredGridLayoutManager.java:2154)
       at androidx.recyclerview.widget.StaggeredGridLayoutManager.scrollVerticallyBy(StaggeredGridLayoutManager.java:2013)
       at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1972)
       at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5476)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
       at android.view.Choreographer.doCallbacks(Choreographer.java:866)
       at android.view.Choreographer.doFrame(Choreographer.java:792)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

设备
品牌：samsung
型号：Galaxy S20+ 5G
屏幕方向： 纵向
可用 RAM： 3.02 GB
可用磁盘空间： 2.71 GB
操作系统
版本：Android 12
屏幕方向： 纵向
是否已取得 root 权限：否
崩溃
日期：2022年8月10日 14:29:28

**Comment by PierfrancescoSoffritti** [comment]
Looks like webview is missing from your device?

**Comment by billdizl** [comment]
maybe,this moile phone is our company' product user,Samsung mobile phone don't have google webview?  i don't believe this.

**Comment by PierfrancescoSoffritti** [comment]
They probably have Google Webview yeah. But I can't say much about that particular device.
