### ISSUE TITLE
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)Caused by android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to verify WebView provider, version code is lower than expected: 506012920 actual: 353811002

### ISSUE THREAD

**Issue by billdizl** [PierfrancescoSoffritti/android-youtube-player#877]
Fatal Exception: android.view.InflateException: Binary XML file line #39: Binary XML file line #39: Error inflating class com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
       at android.view.LayoutInflater.createView(LayoutInflater.java:647)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
       at androidx.databinding.ViewDataBinding.inflateInternal(ViewDataBinding.java:1368)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)Caused by android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to verify WebView provider, version code is lower than expected: 506012920 actual: 353811002
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:423)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
       at android.webkit.WebView.getFactory(WebView.java:2530)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2525)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2590)
       at android.view.View.<init>(View.java:4868)
       at android.view.View.<init>(View.java:5054)
       at android.view.ViewGroup.<init>(ViewGroup.java:597)
       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
       at android.webkit.WebView.<init>(WebView.java:643)
       at android.webkit.WebView.<init>(WebView.java:588)
       at android.webkit.WebView.<init>(WebView.java:571)
       at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.WebViewYouTubePlayer.<init>(WebViewYouTubePlayer.kt:27)

**Comment by Serkali-sudo** [comment]
try updating your webview engine and select system webview by default on the settings.
Uptade this app ->  https://play.google.com/store/apps/details?id=com.google.android.webview
Or you can just use chrome app as webview engine

**Comment by billdizl** [comment]
user don't want, the user webview vesion code is lower than expected: 506012920,this user maybe real conservative

**Comment by Serkali-sudo** [comment]
so if you want to prevent crash without upading webview engine you can put the code causing the crash inside try catch
Like this:
```java
try {
        //put the code here that causing the crash

    } catch (Exception e) {
        if (e.getMessage() != null && e.getMessage().toLowerCase(Locale.ENGLISH).contains("webview")) {
            Toast.makeText(this, "Failed to load webview", Toast.LENGTH_SHORT).show();
        }
    }
```

**Comment by PierfrancescoSoffritti** [comment]
Yes, seems like webview is missing on that device.

**Comment by billdizl** [comment]
&nbsp;i use&nbsp; xml way to use lib, like {
<com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
    android:id="@+id/youtube_player_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_centerVertical="true"
    app:enableAutomaticInitialization="false"/&gt;}



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月15日(星期一) 下午5:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PierfrancescoSoffritti/android-youtube-player] at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)Caused by android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to verify WebView provider, version code is lower than expected: 506012920 actual: 353811002 (Issue #877)





 
so if you want to prevent crash without upading webview engine you can put the code causing the crash inside try catch
 Like this:
 try {         //put the code here that causing the crash     } catch (Exception e) {         if (e.getMessage() != null &amp;&amp; e.getMessage().toLowerCase(Locale.ENGLISH).contains("webview")) {             Toast.makeText(this, "Failed to load webview", Toast.LENGTH_SHORT).show();         }     }
