### ISSUE TITLE
Fatal Exception: android.view.InflateException: Binary XML file line #39

### ISSUE THREAD

**Issue by billdizl** [PierfrancescoSoffritti/android-youtube-player#901]
Fatal Exception: android.view.InflateException: Binary XML file line https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/39: Binary XML file line https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/39: Error inflating class com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
Caused by java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance0(Constructor.java)
at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
at android.view.LayoutInflater.createView(LayoutInflater.java:647)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
at androidx.databinding.ViewDataBinding.inflateInternal(ViewDataBinding.java:1368)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)Caused by android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to verify WebView provider, version code is lower than expected: 506012920 actual: 353811002
at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:423)
at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
at android.webkit.WebView.getFactory(WebView.java:2530)
at android.webkit.WebView.ensureProviderCreated(WebView.java:2525)

**Comment by billdizl** [comment]
no webview install, I found that the user did not install webview.
 so i got a solve this problem idea.  
 may be need u help, mr.PierfrancescoSoffritti
i need change WebViewYouTubePlayer  this lib,  you can extends customer webview  to  throw exception

1. for example:    
 class CrashWebView: WebView {
    constructor(context: Context?) : super(context!!) {}
    constructor(context: Context?, attrs: AttributeSet?) : super(
        context!!, attrs
    ) {
    }

    constructor(context: Context?, attrs: AttributeSet?, defStyleAttr: Int) : super(
        context!!, attrs, defStyleAttr
    ) {
    }

    override fun setOverScrollMode(mode: Int) {
        try {
            super.setOverScrollMode(mode)
        } catch (e: Exception) {
            // 若是发生webview 有关的crash ，则表明system webview 正在更新或者不存在(部分机型上可能存在该问题)
            if (e != null && e.message != null && e.message!!.lowercase(Locale.getDefault())
                    .contains("webview")
            ) {
                e.printStackTrace()
            } else {
                throw e
            }
        }
    }
}

2.    your lib WebViewYouTubePlayer extends CrashWebView    for example:
 internal class WebViewYouTubePlayer constructor(context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0)
    : CrashWebView(context, attrs, defStyleAttr), YouTubePlayer, YouTubePlayerBridge.YouTubePlayerBridgeCallbacks {
}

**Comment by PierfrancescoSoffritti** [comment]
Hi, feel free to fork the library and make the changes you need :)
