### ISSUE TITLE
Application attempted to call on a destroyed WebView

### ISSUE THREAD

**Issue by memobeyle** [PierfrancescoSoffritti/android-youtube-player#961]
Hello,

Is there a way to destroy and reinitialize the YouTube player api as in?

```
Application attempted to call on a destroyed WebView
    java.lang.Throwable
     at org.chromium.android_webview.AwContents.m(chromium-TrichromeWebViewGoogle.aab-stable-556311633:10)
     at com.android.webview.chromium.WebViewChromium.loadUrl(chromium-TrichromeWebViewGoogle.aab-stable-556311633:9)
     at android.webkit.WebView.loadUrl(WebView.java:739)
     at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerImpl.invoke$lambda$2(WebViewYouTubePlayer.kt:62)
     at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerImpl.$r8$lambda$765UGQvtKUt7m2Z71DWbxMJ90pY(Unknown Source:0)
     at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerImpl$$ExternalSyntheticLambda0.run(Unknown Source:6)
     at android.os.Handler.handleCallback(Handler.java:938)
     at android.os.Handler.dispatchMessage(Handler.java:99)
     at android.os.Looper.loop(Looper.java:236)
     at android.app.ActivityThread.main(ActivityThread.java:8057)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```

**Comment by PierfrancescoSoffritti** [comment]
Hi, you can't reuse a WebView that has been destroyed.

**Comment by memobeyle** [comment]
So how do we reset it and recreate it?
I was destorying and rebuilding while using youtube player api before.

**Comment by PierfrancescoSoffritti** [comment]
Why do you need to destroy it? You should provide more information regarding what you're trying to do, otherwise I won't be able to help.

**Comment by memobeyle** [comment]
I host youtube player in fragment.  When I close the activity and open it again, I encounter the error as above.  Normally, when using the android youtube player api, I was destorying the youtube player before fragment destruction and not allowing any bugs to occur.  what I really want to do is to destory and restart whenever I want.  because I am constantly redirecting from app to app and back.  In the meantime, I want to prevent bugs.

**Comment by PierfrancescoSoffritti** [comment]
When the fragment is created a new `YouTubePlayerView` is created. You need to use the `YouTubePlayer` from that.

**Comment by memobeyle** [comment]
This is how I solved it.

`    if (youTubePlayer != null)  {
            youTubePlayer.pause();
            youTubePlayerView.release();
            youTubePlayerView.removeYouTubePlayerListener(youTubePlayerListener);
            youTubePlayer = null;
        }`
