### ISSUE TITLE
DeadObjectException

### ISSUE THREAD

**Issue by deepakjain1989** [PierfrancescoSoffritti/android-youtube-player#991]
# Bug Report

### Description of the Bug
Fatal Exception: java.lang.IllegalStateException: android.os.DeadObjectException
       at com.google.android.youtube.api.jar.client.RemoteEmbeddedPlayer.w(PG:2)
       at afst.ao(PG:2)
       at shx.o(PG:1)
       at com.google.android.apps.youtube.embeddedplayer.service.ui.fullscreen.remoteloaded.b.mH(PG:1)
       at vfy.run(PG:5)
       at android.os.Handler.handleCallback(Handler.java:914)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:225)
       at android.app.ActivityThread.main(ActivityThread.java:7563)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)

### Environment details

Android Version:   Android 8, 9, 10, 11,12
API Version:  compileSdk 33

Tested devices:
10 Model:Redmi 9A
8.1.0 Model:Redmi 5 Plus
10 Model:Redmi Note 7 Pro
8.1.0 Model:Vivo 1724
13 Model:Galaxy M33 5G
11 Model:Realme C3
9 Model:CPH2083
Youtube Player Library Version: 

### Steps to reproduce the bug
---
name: Bug report
about: Use this template for reporting bugs
labels: bug
---

 

# Bug Report

### Environment details

Android Version: 
API Version: 

Tested devices:

Youtube Player Library Version: 

### Additional information
<!-- Provide here further information that might help understand the issue or reproduce the bug, e.g. 
- standalone code snippets of implementation that can copy-pasted and work without any missing classes
- screenshot(s) of visualising the bug
- error logs
- any useful background infromation

**Comment by deepakjain1989** [comment]
Caused by android.os.DeadObjectException:
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:605)
       at far.rp(PG:2)
       at com.google.android.apps.youtube.embeddedplayer.service.service.jar.IApiPlayerService$Stub$Proxy.G(PG:3)
       at com.google.android.youtube.api.jar.client.RemoteEmbeddedPlayer.w(PG:1)
       at afem.ao(PG:2)
       at qtx.f(PG:1)
       at com.google.android.apps.youtube.embeddedplayer.service.ui.fullscreen.remoteloaded.b.mD(PG:1)
       at uko.run(PG:5)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by deepakjain1989** [comment]
i have test around 10 to 15 device unable to reproduce but on Crashlytics getting many issue related to DeadObjectException.
Please guide me to fix it or reproduce it
Thanks in advance
